# Generated by Django 5.1.1 on 2024-09-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adres e-mail"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
            ],
        ),
    ]
