# Generated by Django 5.1.1 on 2024-09-29 20:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
